/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs/troubleshooting'
import { Route as DocsSetupRouteImport } from './routes/docs/setup'
import { Route as DocsMetricsRouteImport } from './routes/docs/metrics'
import { Route as DocsCollectorsRouteImport } from './routes/docs/collectors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/docs/troubleshooting',
  path: '/docs/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSetupRoute = DocsSetupRouteImport.update({
  id: '/docs/setup',
  path: '/docs/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMetricsRoute = DocsMetricsRouteImport.update({
  id: '/docs/metrics',
  path: '/docs/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCollectorsRoute = DocsCollectorsRouteImport.update({
  id: '/docs/collectors',
  path: '/docs/collectors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/collectors': typeof DocsCollectorsRoute
  '/docs/metrics': typeof DocsMetricsRoute
  '/docs/setup': typeof DocsSetupRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/collectors': typeof DocsCollectorsRoute
  '/docs/metrics': typeof DocsMetricsRoute
  '/docs/setup': typeof DocsSetupRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/collectors': typeof DocsCollectorsRoute
  '/docs/metrics': typeof DocsMetricsRoute
  '/docs/setup': typeof DocsSetupRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/collectors'
    | '/docs/metrics'
    | '/docs/setup'
    | '/docs/troubleshooting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/collectors'
    | '/docs/metrics'
    | '/docs/setup'
    | '/docs/troubleshooting'
  id:
    | '__root__'
    | '/'
    | '/docs/collectors'
    | '/docs/metrics'
    | '/docs/setup'
    | '/docs/troubleshooting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsCollectorsRoute: typeof DocsCollectorsRoute
  DocsMetricsRoute: typeof DocsMetricsRoute
  DocsSetupRoute: typeof DocsSetupRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/docs/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/setup': {
      id: '/docs/setup'
      path: '/docs/setup'
      fullPath: '/docs/setup'
      preLoaderRoute: typeof DocsSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/metrics': {
      id: '/docs/metrics'
      path: '/docs/metrics'
      fullPath: '/docs/metrics'
      preLoaderRoute: typeof DocsMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/collectors': {
      id: '/docs/collectors'
      path: '/docs/collectors'
      fullPath: '/docs/collectors'
      preLoaderRoute: typeof DocsCollectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsCollectorsRoute: DocsCollectorsRoute,
  DocsMetricsRoute: DocsMetricsRoute,
  DocsSetupRoute: DocsSetupRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
